DROP SCHEMA IF EXISTS CONGLOMERATE;
CREATE SCHEMA IF NOT EXISTS CONGLOMERATE;
USE CONGLOMERATE;

CREATE TABLE EMPLOYEE (
    FNAME    VARCHAR(15)    NOT NULL,
    MINIT    CHAR,
    LNAME    VARCHAR(15)    NOT NULL,
    SSN    CHAR(9)    NOT NULL,
    BDATE    DATE,
    ADDRESS    VARCHAR(30),
    SEX    CHAR,
    SALARY    DECIMAL(10,2),
    SUPER_SSN    CHAR(9),
    DNO    INT    NOT NULL,
    PRIMARY KEY(SSN),
    FOREIGN KEY(SUPER_SSN) REFERENCES EMPLOYEE(SSN)
);

CREATE TABLE DEPARTMENT (
    DNAME    VARCHAR(15)    NOT NULL,
    DNUMBER    INT    NOT NULL,
    MGR_SSN    CHAR(9)    NOT NULL,
    MGR_START_DATE    DATE,
    PRIMARY KEY(DNUMBER),
    UNIQUE(DNAME),
    FOREIGN KEY(MGR_SSN) REFERENCES EMPLOYEE(SSN)
);

CREATE TABLE DEPT_LOCATIONS (
    DNUMBER INT NOT NULL,
    DLOCATION VARCHAR(15) NOT NULL,
    PRIMARY KEY (DNUMBER , DLOCATION),
    FOREIGN KEY (DNUMBER)
        REFERENCES DEPARTMENT (DNUMBER)
);

